### ISSUE TITLE
Treat functions as Sources

### ISSUE THREAD

**Issue by loreanvictor** [loreanvictor/streamlet#7]
A single parameter function can be treated as a `Source`, reducing syntax overhead of composed sources. This can be achieved by passing [`expr(fn)`](https://github.com/loreanvictor/streamlet/wiki/expr) for each such function `fn` to related transforms / functions.

# Todo:

- [ ] Check whether all type collisions for such a change can be resolved (e.g. by wrapping callbacks in _options_ objects for type disambiguation.
- [ ] Check whether [passive tracking](https://github.com/loreanvictor/streamlet/wiki/expr) can also be folded into the active tracking callback `$` (solution idea: call `$.on` for specifying active trackings in the beginning of the expression, treat all the remaining trackings as passive).
- [ ] Ensure functions passed to `expr()` can be async.
- [ ] Refactor code and change APIs accordingly.
